spring.application.name=blog
spring.security.user.name=admin
spring.security.user.password=your_secure_password
spring.security.user.roles=ADMIN

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
