CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE posts ADD COLUMN author_id INTEGER;

ALTER TABLE posts 
ADD CONSTRAINT fk_posts_author 
FOREIGN KEY (author_id) 
REFERENCES users(id);